// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quake.Data.Database;

namespace Quake.Data.Migrations
{
    [DbContext(typeof(QuakeContext))]
    partial class QuakeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Quake.Data.Entities.Building", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Vrlo oštećena zgrada",
                            Lat = 20.300000000000001,
                            Lng = 13.300000000000001
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Vrlo oštećena zgrada",
                            Lat = 40.299999999999997,
                            Lng = 30.300000000000001
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Manje oštećena zgrada",
                            Lat = -13.300000000000001,
                            Lng = 40.299999999999997
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
